# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FireBaseMLDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FireBaseMLDemo

pod 'Firebase/Core'
pod 'Firebase/MLVision'
# If using the on-device API:
pod 'Firebase/MLVisionTextModel'
pod 'Firebase/MLVisionFaceModel'
pod 'Firebase/MLVisionLabelModel'
pod 'Firebase/MLVisionBarcodeModel'

end
